### ISSUE TITLE
咨询

### ISSUE THREAD

**Issue by junzikai** [wangzuohuai/WebRunLocal#1]
您好，想咨询一下您现在开发到什么进度了？我们想看一下有没有合作的可能性

**Comment by wangzuohuai** [comment]
您好，牛插中间件已经正式发布，已经有一些公司正式采购使用了哦，^_^

**Comment by MYt000QDdgr** [comment]
你好吗，我想使用chrome插件实现调用扫码枪和打印机，替代现有的程序（python调用dill），现在困境是找不到chrome调用dill文件的方法，网络上文档也比较少

**Comment by wangzuohuai** [comment]
http://local.zorrosoft.com/ 我们在线演示和SDK开发包里有调用DLL的范例啊
